### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Operation-Wildfire#1]
Need to get started on testing so we can have this one ready by 13 May.

**Comment by Scotty-Z** [comment]
i would prefer sometime after the 16th when jets is released so mods that are broken can be updated

**Comment by coachwn** [comment]
You have something mod wise that is going to require jets DLC content? So far on dev branch nothing related to base arma is broken from what I can see.

**Comment by coachwn** [comment]
I guess what I am saying is that at least testing it with dev branch content will give us a good idea if something is going to break. I personally think with the call from Dodds for a revitalization of milsim in May that we need a shift towards your mission and a pause of mine.

**Comment by Scotty-Z** [comment]
revitalization as in focusing more in mil-sim than just Arma missions or a restructure?

**Comment by FoxKilo** [comment]
refocus only, no restructures. Something may/may not happen with air but that will be a simple tweak, nothing major. Should be good as is.

**Comment by coachwn** [comment]
The only adjustments are going to be at the command levels of the units. Otherwise we are pushing milsim HARD in May and I think it would be a good thing to press pause on my mission and come back to it.

**Comment by FoxKilo** [comment]
sorry wrong place to do it but just to get this out there, I think pausing an ALiVE would be a very bad idea considering past experiences. What we could do instead is having these "civilians" make the changes with dodds and use a storyline of them forming a Tanoan army, which means we can move along with the current deployment. however that would mean changing the overall direction of the deployment.

So not only do we have the command level reintroducing their structure, training and standards, they're doing it in-game from the ground up with a suitable storyline to keep them in the right spirit.

**Comment by coachwn** [comment]
You know I thought almost as soon as I hit send that it might not be a bad thing to create a DMZ type situation and start a reorganization after they take Ljinhaven. I have the TDF forces already done from my previous Stack Silver campaign and can make them happen or I can drop in US Marines to do the same thing.

**Comment by coachwn** [comment]
Closing this one to ensure we are good for all Scotty mission tests.
