### ISSUE TITLE
Radio channels change when someone respawns 

### ISSUE THREAD

**Issue by Scotty-Z** [Spearhead-Gaming-Milsim/Operation-Wildfire#10]
from what Zen was telling me it is because we all have the same radio ID this is because of scripting the respawns

**Comment by Scotty-Z** [comment]
the only thing I can think of is to minimize the problem but not fix it

**Comment by coachwn** [comment]
I don't think it is the radio ID. I read about this same issue on the TFAR github or BI forum post. I will locate and we can go from there. Also I don't think it is tied to the mission name but I will change that today as well.

**Comment by coachwn** [comment]
[https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1235](url)

**Comment by FoxKilo** [comment]
We've had this issue a few times before and as far I can remember it's always been radio ID and the TFAR module re-initialising globally each time a user is JIP. Try changing the radios from the JEMs to 152s or something. It was also the case that the loadout scripts provided a buffer against this issue.

**Comment by coachwn** [comment]
Just discovered that when I loaded into the game that Battleye did the following:

6/9/2017 12:34:22 PM - Blocked loading of file 'C:\Program Files (x86)\Steam\steamapps\workshop\content\107410\620019431\task_force_radio_pipe_x64.dll'
