### ISSUE TITLE
Roadblocks spawning on runways and sideways on roads

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Operation-Wildfire#13]
[https://steamuserimages-a.akamaihd.net/ugc/833577337133019716/C9565F290E697F917948ECDB11A761270F262CD4/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|2048:1152&composite-to%3D%2A%2C%2A%7C2048%3A1152&background-color=black](url)

[https://steamuserimages-a.akamaihd.net/ugc/833577337133019141/F88F03D8BE8ADD4F78CB24080AE4D6CE9283EFE2/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|2048:1152&composite-to%3D%2A%2C%2A%7C2048%3A1152&background-color=black
](url)

[https://steamuserimages-a.akamaihd.net/ugc/833577337133018567/EAEE223F7F5C661B62BA48A8C5BFC5EA8613C6F6/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|2048:1152&composite-to%3D%2A%2C%2A%7C2048%3A1152&background-color=black](url)

[https://steamuserimages-a.akamaihd.net/ugc/833577337133016931/01DCDFC1A56FA21FD813CF4983E4376A8586EA3F/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|2048:1152&composite-to%3D%2A%2C%2A%7C2048%3A1152&background-color=black](url)

**Comment by Scotty-Z** [comment]
alive bug can't fix

**Comment by coachwn** [comment]
www.github.com/ALiVEOS/ALiVE.OS/issues/360#issuecomment-307366081

Drop by their github and feed them some information.

**Comment by coachwn** [comment]
Should be fixed in latest version of ALiVE which we are using on the server. They are also working on a feature which will make roadblocks that are spawned by ALiVE to be destroyable...is that even a word?
