### ISSUE TITLE
New mortars - Smoke Round issue

### ISSUE THREAD

**Issue by Zntrack** [Spearhead-Gaming-Milsim/Operation-Wildfire#14]
Both 60mm and 80mm Mortar smoke rounds land as HE rounds. When the gunner checked himself, the smoke was visible. We are unsure if the rounds act as HE and can damage enemies/structures or if it acts as smoke rounds with concealment from AI, or neither/both. Further testing needed.

**Comment by FoxKilo** [comment]
The rounds have a small level of explosive charge in them to A) break open the canister on impact and B) rapidly disperse the smoke compound. Rounds should only have a danger close radius of effect for blast wave/shrapnel, though needs testing to see what this radius is.

**Comment by FoxKilo** [comment]
Comments from other users is that the smoke is only showing up client side and only visible representation is the explosion, which is the exact same animation and texture as the HE.

Still need to test the lethality of smoke against flesh and building targets

**Comment by Scotty-Z** [comment]
there is talk on the BI forums about WP rounds or Smoke being updated to Wp, if its a problem I can remove the 81mm

**Comment by Zntrack** [comment]
Scotty buddy no need for extremes here!

Simply documenting this. It doesnt need to be addressed for 1.0. If we find a fix for this down the line itd be great, but its not mission critical.
