### ISSUE TITLE
Check Zeus GUID access.

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Operation-Wildfire#15]
Unable to log into it when I checked newest mission file today.

**Comment by FoxKilo** [comment]
Works fine on my end,  haven't tried the adminlogged one yet. We had this intermittently last deployments and we still don't know what the root cause is.

**Comment by FoxKilo** [comment]
It goes without saying, if it worked before then it's unlikely the GUID in the module is wrong so it's going to come down the initialisation of the module

**Comment by coachwn** [comment]
Admin logged works fine but the other isn't working now....oh well.

**Comment by Scotty-Z** [comment]
doubled check GUID's nothing more i can do

**Comment by FoxKilo** [comment]
After looking at the mission today, we don't need the editing costs module since you're only disabling all the costs anyway. While all costs are disabled with -1 (it recommends a large negative number), this may be preventing consecutive users to access the module due to it's cost.

**Comment by coachwn** [comment]
Let's leave it as is for today. There are several deep seated issues we need to look closer at. The basic functions work and allow the mission to roll on ahead.

**Comment by coachwn** [comment]
Yeah its not worth it...just something we have to deal with as it happens.
