### ISSUE TITLE
AI entity appears when players log off

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Operation-Wildfire#17]
Saw more than one instance of an AI Afrene soldier attached to Infantry or walking alone across the map. Might want to check out what was creating them in past missions and what fixed it.

**Comment by FoxKilo** [comment]
This was previously a BI bug which was patched about 2 months ago. Only other time this would happen is if the mission was treating players as a single player entity, as when you log out of missions your slot turns back to AI when vacant.

**Comment by coachwn** [comment]
Another instance of things that were copied from the older Chernarus style...fixed now.
