### ISSUE TITLE
OP Wildfire mission testing

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Operation-Wildfire#2]
In order to test for full release. All units testing should start with respawn and loadouts; then proceed ahead with testing AI responsiveness and AI spawns. Do not proceed in full force go kill mode...this is the initial test aspect so work it out on your own at the moment. We will put the test mission up for full testing this week.

DO NOT MAKE REQUESTS OF MISSION MAKER ON ADDING NEW STUFF.

**Comment by Scotty-Z** [comment]
link to the steam collection
http://steamcommunity.com/sharedfiles/filedetails/?id=912680790

**Comment by coachwn** [comment]
30.4GB!?!? Total modpack size.

**Comment by coachwn** [comment]
First test launch was a failure since it didn't have Ares-Achilles loaded...adding that back in and starting again.

**Comment by coachwn** [comment]
@Scotty-Z Please check through your stuff for this one. PW to server is Chibuku and check your PM for admin pw.

Server is up and running now...odd error message on server console load though.

 8:45:26 Dedicated host created.
 8:45:49 BattlEye Server: Initialized (v1.215)
 8:45:49 Host identity created.
 8:45:49 Game Port: 2340, Steam Query Port: 2341
 8:45:49 Mission OP_Wildfire.IslaDuala3 read from bank.
 8:45:49 Roles assigned.
 8:45:49 Reading mission ...
 **_8:46:00 No entry 'bin\config.bin/CfgVehicles/Plane_Base_F/HitPoints/HitHull.name'._**
 8:46:00 Mission OP_Wildfire.IslaDuala3 read from bank.
 8:46:01 Roles assigned.
 8:46:01 Reading mission ...
 8:46:07 Mission read.
 8:46:07 Game started.

**Comment by coachwn** [comment]
Also getting reports that the rh_acc and rh_de compats are out dated...might be due to user error but just in case check your compat files and make sure they are loaded with the most recent version of ACE which is 3.9.2

**Comment by Scotty-Z** [comment]
mod pack is the same size as Queen's Stallions

No entry 'bin\config.bin/CfgVehicles/Plane_Base_F/HitPoints/HitHull.name'. is an error with TFR and firewills A10

will double check Ace Compats

**Comment by Scotty-Z** [comment]
RH_ACC is up to date RH_DE is not used

**Comment by coachwn** [comment]
Pushing new test version tonight.

**Comment by coachwn** [comment]
Same error still exists from yesterday when starting the mission with the "Plane_Base"; not sure what it relates to though.

**Comment by KingHeavy** [comment]
Alright, some comments for Cav equipment, otherwise all is working well enough. The only things we have left to test is how effective the mortars we have are, and the gpmg. I've already confirmed the mg3 is glorious and golden. Anyways, we are lacking M1911A1, FR Ordinance MC51 (armor crew weapons), and M24 SWS ammo in our boxes, and would like to know if ACE Logistics is setup and functioning. Thanks.

**Comment by Scotty-Z** [comment]
will  add g3 ammo and 1911 mags @KingHeavy M24 ammo is in the box it's towards the bottom

**Comment by FoxKilo** [comment]
Check logistics - not working
