### ISSUE TITLE
Check ACE logistics

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Operation-Wildfire#21]
ACE logistics not working properly. Needs to be checked and verified that it works as it should; as it stands we are unable to transport items via vehicles.

**Comment by Hauser1** [comment]
There is a check box in one of the ACE logistics modules that either allows things to be transported or allows vehicles to have an inventory I believe, so that may be a place to start.

**Comment by coachwn** [comment]
I don't think the correct module is down for the cargo. I am checking it again tonight.

**Comment by coachwn** [comment]
No clue why it isn't working corrrectly....have checked everything and its just weird. Maybe overlooking something but I am moving on and closing this issue.
