### ISSUE TITLE
Way too many civilians spawning up in the northern side of DMZ and AI not virtualizing again

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Operation-Wildfire#24]
Looking into a fix for this and going to take some time this afternoon to tweak it and see what happens on my test box. Also wondering why they aren't getting virtualized after they spawn in? This is also happening with the AI for FMM and FMA as well. We had an operation up near Djoline and points west on Saturday and then a bunch of guys went down to the southeast side of the map. The AI was still spawned in up north with no players in the area.

**Comment by FoxKilo** [comment]
Issue has been present for the last couple of deployments, especially leaving ambient civ vehicles etc after players leave the area. Haven't looked into it too much but guessing it's an ALiVE problem since the last major update.

**Comment by coachwn** [comment]
[https://github.com/ALiVEOS/ALiVE.OS/issues/364](url) cross linked to ALiVE Github in case they can come up with an answer.
