### ISSUE TITLE
Loadout controller outdated

### ISSUE THREAD

**Issue by Jmaster9999** [Spearhead-Gaming-Milsim/Operation-Wildfire#4]
The version of load-out controller you are using is depreciated and has a critical bug. You should update to the latest version whenever possible. If you need help updating, send me a message on teamspeak or I could to it for you.

This loadout controller bug greatly affects client performance and destroys frame-rates. (this is due to an infinite loop, that gets spawned each time a player dies). This bug has since been patched and is no longer an issue in the latest versions. Additionally newer versions of loadout controller use eventhandlers which further increases performance.

**Comment by Scotty-Z** [comment]
not use it its just there
