### ISSUE TITLE
Stamina

### ISSUE THREAD

**Issue by dragonlife284** [Spearhead-Gaming-Milsim/Operation-Wildfire#9]
A glitch that used to happen before is happening again where stamina does not come back, at all, even if you drop all of your kit.  Additionally, we're back to having minor wounds of any kind to the arms completely ruin aim. This hasn't been a problem in recent deployments, so I believe it has something to do with the settings for medical.

**Comment by Scotty-Z** [comment]
tweaked settings

**Comment by Scotty-Z** [comment]
Removed Ace's advance fatigue as I believe it was interfering with Advance movent's fatigue system causing the problem
